import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundImage: `url(bg.jpg)`, backgroundSize: "cover" }}>
        <div className="text-white top-0 w-full fixed flex justify-center z-50 bg-red-700">
          Huong Duy Anh
        </div>
        {children}
      </body>
    </html>
  );
}
