import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { useState } from "react";
import Header from "./Component/header";
import { SwitchProvider, useSwitch } from "./SwitchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" w-full h-full flex justify-center">
        <SwitchProvider>
          <div className="w-[428px] justify-center flex ">
            <Header />
            {children}
          </div>
        </SwitchProvider>
      </body>
    </html>
  );
}
